### PR TITLE
fix build on MAC

### PR DESCRIPTION
**Pull request by volvet**
the master code can't be build,  include  mainenc.h is missing.    this patch intend to fix the build issue.

### CODE REVIEW

**Comment by knitori** [comment]
It's in `strings.h` though?

**Comment by volvet** [comment]
@knitori,  below is build error on my MAC,  after add the include,  the error gone.     
 In addition, Build Intrinsics also have issues,   change -O0 want to suppress intrinsics issues.   

QIZH-M-L00F:thor volvet$ make
cc -std=c99 -g -O0 -Wall -pedantic -I common -c -o enc/strings.o enc/strings.c
enc/strings.c:137:48: error: unknown type name 'enc_params'
static int parse_params(int argc, char **argv, enc_params *params, param_list *list)
                                               ^
enc/strings.c:267:1: error: unknown type name 'enc_params'
enc_params *parse_config_params(int argc, char **argv)
^
enc/strings.c:271:3: error: use of undeclared identifier 'enc_params'
  enc_params *params;
  ^
enc/strings.c:271:15: error: use of undeclared identifier 'params'
  enc_params *params;
              ^
enc/strings.c:276:3: error: use of undeclared identifier 'params'
  params = (enc_params *)malloc(sizeof(enc_params));
  ^
enc/strings.c:276:13: error: use of undeclared identifier 'enc_params'
  params = (enc_params *)malloc(sizeof(enc_params));
            ^
enc/strings.c:276:25: error: expected expression
  params = (enc_params *)malloc(sizeof(enc_params));
                        ^
enc/strings.c:277:7: error: use of undeclared identifier 'params'
  if (params == NULL)
      ^
enc/strings.c:283:10: error: use of undeclared identifier 'params'
  memset(params, 0, sizeof(enc_params));
         ^
/usr/include/secure/_string.h:77:27: note: expanded from macro 'memset'
  __builtin___memset_chk (dest, val, len, __darwin_obsz0 (dest))
                          ^
enc/strings.c:283:28: error: use of undeclared identifier 'enc_params'
  memset(params, 0, sizeof(enc_params));
                           ^
/usr/include/secure/_string.h:77:38: note: expanded from macro 'memset'
  __builtin___memset_chk (dest, val, len, __darwin_obsz0 (dest))
                                     ^
enc/strings.c:283:10: error: use of undeclared identifier 'params'
  memset(params, 0, sizeof(enc_params));
         ^
/usr/include/secure/_string.h:77:59: note: expanded from macro 'memset'
  __builtin___memset_chk (dest, val, len, __darwin_obsz0 (dest))
                                                          ^
/usr/include/secure/_common.h:38:55: note: expanded from macro '__darwin_obsz0'
#define __darwin_obsz0(object) __builtin_object_size (object, 0)
                                                      ^
enc/strings.c:287:74: error: use of undeclared identifier 'params'
  add_param_to_list(&list, "-if",                   NULL, ARG_FILENAME, &params->infilestr);
                                                                         ^
enc/strings.c:288:74: error: use of undeclared identifier 'params'
  add_param_to_list(&list, "-ph",                    "0", ARG_INTEGER,  &params->file_headerlen);
                                                                         ^
enc/strings.c:289:74: error: use of undeclared identifier 'params'
  add_param_to_list(&list, "-fh",                    "0", ARG_INTEGER,  &params->frame_headerlen);
                                                                         ^
enc/strings.c:290:74: error: use of undeclared identifier 'params'
  add_param_to_list(&list, "-of",                   NULL, ARG_FILENAME, &params->outfilestr);
                                                                         ^
enc/strings.c:291:74: error: use of undeclared identifier 'params'
  add_param_to_list(&list, "-rf",                   NULL, ARG_FILENAME, &params->reconfilestr);
                                                                         ^
enc/strings.c:292:74: error: use of undeclared identifier 'params'
  add_param_to_list(&list, "-stat",                 NULL, ARG_FILENAME, &params->statfilestr);
                                                                         ^
enc/strings.c:293:74: error: use of undeclared identifier 'params'
  add_param_to_list(&list, "-n",                   "600", ARG_INTEGER,  &params->num_frames);
                                                                         ^
enc/strings.c:294:74: error: use of undeclared identifier 'params'
  add_param_to_list(&list, "-skip",                  "0", ARG_INTEGER,  &params->skip);
                                                                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [enc/strings.o] Error 1

**Comment by tdaede** [comment]
The problem here is that strings.h is a standard BSD header name, and so the compiler is picking up that rather than the one included in Thor. The solution here is to rename strings.[c|h] in Thor.

**Comment by volvet** [comment]
@tdaede,   rename is better for #17.   I can raise a new pull request for it.

**Comment by volvet** [comment]
closed as #18 raised.

**Pull request closed without merging**
